name = "strongcall"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-04-05"
account_id = "2a03f81f83258cf4285679d0a4eef805"
main = "./build/index.js"

[site]
  bucket = "./public"

[[build.upload.rules]]
  type = "ESModule"
  globs = ["**/*.js"]

[vars]
CALLS_APP_ID = "31e32c538c76dd1176d2ad9a87991a54"

[durable_objects]
 bindings = [
  { name = "rooms", class_name = "ChatRoom" }
]

# Indicate that you want the ChatRoom class to be callable as Durable Objects.
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["ChatRoom"]

# The necessary secrets are:
# - CALLS_APP_SECRET
# To add secret, run `echo <VALUE> | wrangler secret put <NAME>`
